### PR TITLE
Redesign `Settings`

### PR DESCRIPTION
**Pull request by bvssvni**
* Added `Flip` enum
* Removed `force_alpha` (since it is not implemented)
* Moved `Settings` to `TextureSettings` in piston-texture
* Implemented `Rgba8Texture` for `Texture`

### CODE REVIEW

**Comment by bvssvni** [comment]
I wonder if we should move `Settings` to the `texture` lib and land the redesign @Potpourri suggested https://github.com/PistonDevelopers/texture/pull/24

**Comment by bvssvni** [comment]
I think `flip_vertical` should be removed and performed manually using `texture::ops::flip_vertical`.

**Comment by bvssvni** [comment]
Alternatively this can be done manually with `image::imageops::flip_vertical`.

**Comment by bvssvni** [comment]
Now I get why `flip_vertical` was needed. It is for loading image from path.

**Comment by bvssvni** [comment]
We could have a generic library for loading textures.

**Comment by bvssvni** [comment]
Could add a `Flip` enum and use it as an extra parameter in from_path:

```Rust
pub enum Flip {
    None,
    Vertical,
}
```

**Comment by kvark** [comment]
:+1:

**Comment by bvssvni** [comment]
Ok, merging.

**Pull request merged**
