### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by bvssvni**
- Bumped to 0.15.0

### CODE REVIEW

**Comment by kvark** [comment]
Why do you specify the exact revision though? I'd think that it only makes sense to say `0.3.1` when it doesn't work with prior patched versions, and otherwise you'd just want `0.3`. Same for other deps.

**Comment by bvssvni** [comment]
You don't have to. I put in the latest version to get bug fixes.

**Comment by kvark** [comment]
But it does pick `0.3.1` automatically if your dependency is written as `0.3`, right?

**Comment by bvssvni** [comment]
Only when you build the project first time, I think. After that it needs `cargo update`.

**Pull request merged**
